workflows:
  imaplay:
  name: imaplay
  instance_type: mac_pro
  max_build_duration: 100
    environment:
      groups:
        - keystore_credentials
        - app_store_credentials
      vars:
        GOOGLE_PLAY_TRACK: "beta"
      ionic: stable
      xcode: latest
      cocopods: 1.9.1
      node: 12.14.0
      npm: 6.13.7
      ndk: r21d
      java: 1.8
      ruby: 2.7.2
