workflows:
  imaplay:
    environment:
      groups:
        - keystore_credentials
        - app_store_credentials
      vars:
        GOOGLE_PLAY_TRACK: "beta"
      flutter: stable
      xcode: latest
      node: 12.14.0
      npm: 6.13.7
      ndk: r21d
      java: 1.8
      ruby: 2.7.2
